# Origin: https://github.com/ah-/rdkafka-dotnet

language: csharp

os:
   - osx
   - linux

env:
   - RUNTIME=mono
   - RUNTIME=coreclr

# TODO on linux: install http://docs.confluent.io/2.0.0/installation.html#installation-apt

install:
   - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
   - dnvm upgrade
   - dnvm install -r $RUNTIME 1.0.0-rc1-update1
   - dnvm use -r $RUNTIME 1.0.0-rc1-update1
   - dnu restore

script:
    - ./build/copy-runtimes.sh
    - if [ $RUNTIME == "coreclr" ]
      then
        dnu build ./src/RdKafka/project.json --framework dotnet5.4
      else
        dnu build
      fi
    - dnu pack ./src/RdKafka/project.json
    - dnx -p ./test/RdKafka.Tests/ test
