# Origin: https://github.com/ah-/rdkafka-dotnet

language: csharp
sudo: required
dist: trusty

os:
   - linux

install:
   - if [ "$TRAVIS_OS_NAME" == "linux" ]; then curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version 1.0.0-preview1-002702 --install-dir ~/dotnet ; fi
   - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo ln -s ~/dotnet/dotnet /usr/local/bin; fi
   - dotnet restore

script:
   - dotnet build ./src/RdKafka/project.json
   - dotnet pack ./src/RdKafka/project.json
   - dotnet test ./test/RdKafka.Tests/
