os: Visual Studio 2015

build_script:
  - cmd: set DNX_BUILD_VERSION=%APPVEYOR_BUILD_NUMBER%
  - cmd: dnu restore
  - cmd: dnu build ./src/RdKafka/project.json
  - cmd: dnu pack ./src/RdKafka/project.json --configuration release
  - cmd: dnx -p ./test/RdKafka.Tests/ test

artifacts:
  - path: ./src/RdKafka/bin/release/*.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: qbl3uvq1riFSNeRw6/MHnaDbJ0Ft9evEcz3nQp061pKEhXn0ex4eI56dwUOO2fWF
  skip_symbols: true
  artifact: ./src/RdKafka/bin/release/*.nupkg