os: Visual Studio 2015

configuration:
- Release

install:
- ps: Start-FileDownload 'https://download.microsoft.com/download/4/6/1/46116DFF-29F9-4FF8-94BF-F9BE05BE263B/packages/DotNetCore.1.0.0.RC2-SDK.Preview1-x64.exe'
- cmd: DotNetCore.1.0.0.RC2-SDK.Preview1-x64.exe /quiet

environment:
  PATH: $(PATH);$(PROGRAMFILES)\dotnet\

build_script:
  - appveyor-retry dotnet restore -v Minimal
  - dotnet build **/project.json -c %CONFIGURATION%
  - dotnet pack src/RdKafka/project.json -c %CONFIGURATION% --version-suffix %APPVEYOR_BUILD_NUMBER%
  - dotnet test test/RdKafka.Tests

test: off

artifacts:
  - path: ./src/RdKafka/bin/Release/*.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: qbl3uvq1riFSNeRw6/MHnaDbJ0Ft9evEcz3nQp061pKEhXn0ex4eI56dwUOO2fWF
  skip_symbols: true
  artifact: /.*\.nupkg/
